config/routes.rb
Rails.application.routes.draw do
  resources :potatos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potato.rb
class Potato < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/potatos_controller.rb
class PotatosController < ApplicationController


    def index
      @potatos = Potato.all
    end

    def show
      @potato = Potato.find(params[:id])
    end

    def new
      @potato = Potato.new
    end

    def edit
      @potato = Potato.find(params[:id])
    end

    def create
      @potato = Potato.create(potato_params)
      flash[:message] = "Successfully created potato."
      redirect_to @potato
    end

    def update
      @potato = Potato.update(potato_params)
      redirect_to potato_path(@potato)
    end

    def destroy
      @potato = Potato.find(params[:id]).destroy
      redirect_to potatos_path
    end

    private

    def potato_params()
      params.require(:potato).permit(:name, :eyes)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/potatos_helper.rb
module PotatosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudLecture</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/potatos/edit.html.erb
<h1>Edit Potato</h1>

<%= form_for(@potato) do |f| %>

  <div><%= f.label :name %> <br>
      <%= f.text_field :name %>
  </div> <br>

  <div><%= f.label :eyes %> <br>
      <%= f.number_field :eyes %>
  </div> <br>

  <%= f.submit %>

<% end %>

<%= link_to "Back", potatos_path %> | <%= link_to "Show", potatos_path(@potato) %>

app/views/potatos/index.html.erb
<h1>Potatoes</h1>
  <ol>
<% @potatos.each do |potato| %>


    <li><%= link_to potato.name, potato_path(potato) %> <%= link_to "Edit", edit_potato_path(potato) %></li>

    <%= form_tag potato_path(potato.id), method: "delete" %>
    <%= submit_tag "Delete #{potato.name}" %>

<% end %>
  </ol>

  <p><%= link_to "New Potato", new_potato_path %></p>

app/views/potatos/new.html.erb
<h1>New Potato</h1>

<%= form_for(@potato) do |f| %>

  <div><%= f.label :name %> <br>
      <%= f.text_field :name %>
  </div> <br>

  <div><%= f.label :eyes %> <br>
      <%= f.text_field :eyes %>
  </div> <br>

  <%= f.submit %>

<% end %>

app/views/potatos/show.html.erb
<%# if flash.has?(:message) %>
<p><%= flash[:message] %><p>
<%# end %>

<p> <strong>Name:</strong> <%= @potato.name %> </p>
<p> <strong>Eyes:</strong> <%= @potato.eyes %> </p>

<%= link_to "Edit", edit_potato_path(@potato) %> | <%= link_to "Back", potatos_path %>